{{/* Render an HPA for the component when hpa.enabled is true. */}}
{{- define "cos-common.hpa" -}}
{{- $vals := default dict .values -}}
{{- $hpa := default dict $vals.hpa -}}
{{- $componentEnabled := include "cos-common.componentEnabled" (dict "values" $vals) | fromYaml -}}
{{- $render := and $componentEnabled (default false $hpa.enabled) -}}
{{- if $render }}
{{- $labels := merge (dict) (default (dict) $vals.labels) (default (dict) $hpa.labels) -}}
{{- $annotations := include "cos-common.annotations" (dict "values" $vals "resource" $hpa.annotations) | fromJson -}}
{{- $fullnameOverride := coalesce $hpa.name $hpa.fullnameOverride $vals.fullnameOverride -}}
{{- $scaleTargetDefaults := dict "apiVersion" "apps/v1" "kind" "Deployment" -}}
{{- $scaleTarget := merge $scaleTargetDefaults (default (dict) $hpa.scaleTargetRef) -}}
{{- $targetName := coalesce $hpa.scaleTargetName $scaleTarget.name (include "cos-common.fullname" (dict "root" .root "name" .name "values" $vals)) -}}
{{- $metrics := $hpa.metrics -}}
{{- if not $metrics }}
{{- $metrics = list (dict "type" "Resource" "resource" (dict "name" "cpu" "target" (dict "type" "Utilization" "averageUtilization" 70))) -}}
{{ end }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  {{- include "cos-common.metadata" (dict "root" .root "name" .name "values" (dict "fullnameOverride" $fullnameOverride "labels" $labels "annotations" $annotations)) | nindent 2 }}
spec:
  {{- /* Default target: the Deployment generated by this component unless overridden. */}}
  scaleTargetRef:
    apiVersion: {{ default "apps/v1" $scaleTarget.apiVersion }}
    kind: {{ default "Deployment" $scaleTarget.kind }}
    name: {{ $targetName }}
  minReplicas: {{ default 1 $hpa.minReplicas }}
  maxReplicas: {{ default 1 $hpa.maxReplicas }}
  {{- /* Provide a sane CPU target if none supplied to avoid schema errors. */}}
  metrics:
    {{- range $metric := $metrics }}
    - {{ tpl (toYaml $metric) $.root | nindent 6 }}
    {{ end }}
  {{- with $hpa.behavior }}
  behavior:
    {{- tpl (toYaml .) $.root | nindent 4 }}
  {{ end }}
{{ end }}
{{ end }}
